// SPDX-License-Identifier: LicenseRef-PYRAX-Proprietary
//
// GENERATED by scripts/gen-docs-index.cjs from docs-data.ts — do not edit by hand.
// A lightweight title/slug index of every docs page, so the command palette can search docs
// without importing the heavy docs-data.ts on every page. Re-run the generator when docs change.
export type DocIndexEntry = { slug: string; title: string; category: string };
export const DOC_INDEX: DocIndexEntry[] = [
  { slug: "introduction", title: "Introduction", category: "Get Started" },
  { slug: "getting-started", title: "Getting started", category: "Get Started" },
  { slug: "networks", title: "Networks & endpoints", category: "Get Started" },
  { slug: "accounts-and-storage", title: "Accounts & storage", category: "Concepts" },
  { slug: "transactions", title: "Transactions", category: "Concepts" },
  { slug: "gas-and-fees", title: "Gas & fees", category: "Concepts" },
  { slug: "consensus", title: "Consensus", category: "Concepts" },
  { slug: "vms-overview", title: "Virtual Machines: Overview", category: "Virtual Machines" },
  { slug: "evm", title: "EVM (Solidity)", category: "Virtual Machines" },
  { slug: "wasm-overview", title: "WASM (Overview)", category: "Virtual Machines" },
  { slug: "wasm-rust", title: "WASM: Rust SDK", category: "Virtual Machines" },
  { slug: "wasm-assemblyscript", title: "WASM: AssemblyScript", category: "Virtual Machines" },
  { slug: "wasm-tinygo", title: "WASM: TinyGo", category: "Virtual Machines" },
  { slug: "cairo", title: "Cairo", category: "Virtual Machines" },
  { slug: "connect-tooling", title: "Connect your tooling", category: "Guides" },
  { slug: "deploy-and-call", title: "Deploy and call a contract", category: "Guides" },
  { slug: "events-and-logs", title: "Events & logs", category: "Guides" },
  { slug: "cross-vm-calls", title: "Cross-VM calls", category: "Guides" },
  { slug: "create2", title: "Deterministic deploys with CREATE2", category: "Guides" },
  { slug: "local-dev-and-testing", title: "Local dev & testing", category: "Guides" },
  { slug: "json-rpc", title: "JSON-RPC reference", category: "Reference" },
  { slug: "precompiles", title: "Precompiles reference", category: "Reference" },
  { slug: "wasm-host-abi", title: "WASM host ABI reference", category: "Reference" },
  { slug: "rust-sdk", title: "Rust SDK reference (pyrax-contract-sdk)", category: "Reference" },
  { slug: "cairo-syscalls", title: "Cairo syscall reference", category: "Reference" },
  { slug: "bridge", title: "L1↔rollup bridge reference", category: "Reference" },
  { slug: "gas-and-limits", title: "Gas & limits reference", category: "Reference" },
  { slug: "errors-and-glossary", title: "Errors & glossary", category: "Reference" },
  { slug: "neurax-overview", title: "NEURAX — Overview", category: "Build with NEURAX" },
  { slug: "neurax-models", title: "NEURAX — Model Catalog", category: "Build with NEURAX" },
  { slug: "neurax-route-cli", title: "NEURAX — The neurax-route CLI", category: "Build with NEURAX" },
  { slug: "neurax-gateway", title: "NEURAX — The Gateway", category: "Build with NEURAX" },
  { slug: "neurax-economy", title: "NEURAX — Economy & Settlement", category: "Build with NEURAX" },
];
