# SPDX-License-Identifier: LicenseRef-PYRAX-Proprietary
# Explorer frontend only. /api/* is routed to the indexer by Caddy (it never reaches nginx).
server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri.html $uri/ /index.html;
  }
  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }
  location ~* \.html$ {
    add_header Cache-Control "no-cache";
  }

  gzip on;
  gzip_comp_level 6;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml application/wasm;
}
